//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istoria
    {
        public int ID_Istoria { get; set; }
        public Nullable<int> ID_Klient { get; set; }
        public Nullable<int> ID_Zakaz { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
