//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int ID { get; set; }
        public string Naimenovanie { get; set; }
        public Nullable<int> ID_Kategoria { get; set; }
        public Nullable<int> Max_Srok_Hranenia { get; set; }
        public Nullable<int> Min_Ostatok { get; set; }
        public Nullable<int> ID_Mesta_Hranenia { get; set; }
        public Nullable<int> ID_Otvet_sotrudnica { get; set; }
    
        public virtual Kategoria Kategoria { get; set; }
        public virtual Mesta_Hranenia Mesta_Hranenia { get; set; }
        public virtual Sotrudnic Sotrudnic { get; set; }
    }
}
