//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavcik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postavcik()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int ID_Postavcik { get; set; }
        public string UR_Nazvanie { get; set; }
        public string UR_Adres { get; set; }
        public Nullable<int> INN { get; set; }
        public Nullable<int> Number_Dogovor { get; set; }
        public Nullable<int> Kod_OKPO { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> Kontakt_Otvet_Lica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
