//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazanie_Preparat
    {
        public int ID_Zakaz_Prepatatov { get; set; }
        public Nullable<int> ID_Preparat { get; set; }
        public Nullable<int> ID_Zakaza { get; set; }
    
        public virtual Preparat Preparat { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
