//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.Istoria = new HashSet<Istoria>();
            this.Zakazanie_Preparat = new HashSet<Zakazanie_Preparat>();
        }
    
        public int ID_Zakaz { get; set; }
        public Nullable<System.DateTime> Data_Zakaz { get; set; }
        public Nullable<System.DateTime> Data_Otgruzki { get; set; }
        public Nullable<int> Kolihestvo { get; set; }
        public Nullable<int> ID_Postavcik { get; set; }
        public Nullable<int> ID_Klient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Istoria> Istoria { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Postavcik Postavcik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakazanie_Preparat> Zakazanie_Preparat { get; set; }
    }
}
