//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapis
    {
        public int ID_Zapisi { get; set; }
        public Nullable<int> ID_klienta { get; set; }
        public Nullable<int> ID_Spec_Sotrudnic { get; set; }
        public Nullable<int> ID_Dogovora { get; set; }
    
        public virtual Dogovor Dogovor { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Sotrudnic Sotrudnic { get; set; }
    }
}
